export enum AppView {
    LANDING = 'LANDING',
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    DASHBOARD = 'DASHBOARD',
    UPLOAD = 'UPLOAD',
    HISTORY = 'HISTORY',
    LIKED = 'LIKED',
    VIDEO_DETAIL = 'VIDEO_DETAIL',
    STATS = 'STATS'
}
